538 : 2018-08-16 21:54:10,466 : INFO : telemetry.main : Attempt start. Configuration directory [/root/.azure].
538 : 2018-08-16 21:54:10,466 : INFO : telemetry.check : Positive: The /root/.azure/telemetry.txt does not exist.
538 : 2018-08-16 21:54:10,466 : DEBUG : telemetry.note : acquiring lock
538 : 2018-08-16 21:54:10,466 : DEBUG : telemetry.note : acquired lock
538 : 2018-08-16 21:54:10,467 : INFO : telemetry.note : Update the note mtime to 2018-08-16 21:54:10.466991
538 : 2018-08-16 21:54:10,467 : WARNING : telemetry.note : Fail to parse or read the timestamp 'N/A' in the note file. Set the last send time to minimal. Reason: File not open for reading
538 : 2018-08-16 21:54:10,467 : INFO : telemetry.records : No cache to be uploaded.
538 : 2018-08-16 21:54:10,467 : INFO : telemetry.client : Accumulated 0 events. Flush the clients.
538 : 2018-08-16 21:54:10,467 : ERROR : telemetry.main : Unexpected Error year=1 is before 1900; the datetime strftime() methods require year >= 1900. Exit 2.
538 : 2018-08-16 21:54:10,467 : ERROR : telemetry.main : year=1 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (most recent call last):
  File "/tmp/pip-install-2Sixsg/azure-cli-telemetry/azure/cli/telemetry/__init__.py", line 101, in main
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/telemetry/components/telemetry_note.py", line 54, in update_telemetry_note
    self.fh.write(next_send.strftime('%Y-%m-%dT%H:%M:%S'))
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
30 : 2019-03-13 10:08:23,815 : INFO : telemetry.main : Attempt start. Configuration directory [/root/.azure].
30 : 2019-03-13 10:08:23,815 : INFO : telemetry.check : Returns Positive.
30 : 2019-03-13 10:08:23,816 : DEBUG : telemetry.note : acquiring lock
30 : 2019-03-13 10:08:23,816 : DEBUG : telemetry.note : acquired lock
30 : 2019-03-13 10:08:23,816 : INFO : telemetry.note : Update the note mtime to 2019-03-13 10:08:23.816252
30 : 2019-03-13 10:08:23,820 : WARNING : telemetry.note : Fail to parse or read the timestamp '' in the note file. Set the last send time to minimal. Reason: time data '' does not match format '%Y-%m-%dT%H:%M:%S'
30 : 2019-03-13 10:08:23,820 : INFO : telemetry.records : No cache to be uploaded.
30 : 2019-03-13 10:08:23,820 : INFO : telemetry.client : Accumulated 0 events. Flush the clients.
30 : 2019-03-13 10:08:23,820 : ERROR : telemetry.main : Unexpected Error year=1 is before 1900; the datetime strftime() methods require year >= 1900. Exit 2.
30 : 2019-03-13 10:08:23,821 : ERROR : telemetry.main : year=1 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (most recent call last):
  File "/tmp/pip-install-2Sixsg/azure-cli-telemetry/azure/cli/telemetry/__init__.py", line 101, in main
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/telemetry/components/telemetry_note.py", line 54, in update_telemetry_note
    self.fh.write(next_send.strftime('%Y-%m-%dT%H:%M:%S'))
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
77 : 2019-03-13 10:54:29,727 : INFO : telemetry.main : Attempt start. Configuration directory [/root/.azure].
77 : 2019-03-13 10:54:29,728 : INFO : telemetry.check : Returns Positive.
77 : 2019-03-13 10:54:29,728 : DEBUG : telemetry.note : acquiring lock
77 : 2019-03-13 10:54:29,728 : DEBUG : telemetry.note : acquired lock
77 : 2019-03-13 10:54:29,728 : INFO : telemetry.note : Update the note mtime to 2019-03-13 10:54:29.728697
77 : 2019-03-13 10:54:29,730 : WARNING : telemetry.note : Fail to parse or read the timestamp '' in the note file. Set the last send time to minimal. Reason: time data '' does not match format '%Y-%m-%dT%H:%M:%S'
77 : 2019-03-13 10:54:29,735 : INFO : telemetry.records : No cache to be uploaded.
77 : 2019-03-13 10:54:29,735 : INFO : telemetry.client : Accumulated 0 events. Flush the clients.
77 : 2019-03-13 10:54:29,735 : ERROR : telemetry.main : Unexpected Error year=1 is before 1900; the datetime strftime() methods require year >= 1900. Exit 2.
77 : 2019-03-13 10:54:29,735 : ERROR : telemetry.main : year=1 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (most recent call last):
  File "/tmp/pip-install-2Sixsg/azure-cli-telemetry/azure/cli/telemetry/__init__.py", line 101, in main
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/telemetry/components/telemetry_note.py", line 54, in update_telemetry_note
    self.fh.write(next_send.strftime('%Y-%m-%dT%H:%M:%S'))
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
